name: Conda package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  try-setup-miniconda:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true
          auto-update-conda: true
          conda-build-version: '*'
          miniconda-version: latest
          activate-environment: my_test
          python-version: '3.10'
      - name: Display conda info
        run: conda info
      - name: Display conda list
        run: conda list -n my_test
      - name: Install package
        run: |
          conda install -n my_test threadpoolctl 
      - name: Display conda list
        run: |
          conda list -n my_test
