name: Conda package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  try-setup-miniconda:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true
          auto-update-conda: true
          conda-build-version: '*'
          miniconda-version: 'latest'
          activate-environment: my_test
          python-version: '3.10'
      - name: Display conda data
        run: |
          conda info
          conda list
      - name: Install package
        run: |
          conda install -c dppy/label/dev -c intel dpctl 
          conda info
          conda list
      - name: Display conda data
        run: |
          conda info
          conda list
